<tr class="list-item-new">
    <td width="20%" align="right" style="padding:5px;">
        <div class="image-message">
            <a href="/profile/of/{{ note.profile.username }}">
            <img src="{{ note.profile.picture_public }}" width="100%" height="100%"/>
            </a>
        </div>
    </td>
    <td width="80%">
        <div>
            <span class="flag-icon flag-icon-ca user-country"></span>
            <h2 class="title-new inline">
                <a class="action-profile user-title" href="/profile/of/{{ name }}">@{{ name }}</a>
            </h2>
            <span class="ion-female user-genre female"></span>
            <span class="notes-time">| {{ inserted }}</span>
        </div>
        <p class="note">
            {{ text }}
        </p>

        <div class="buttons-section">
            <a class="action category-link" href="#" data-action="like/{{ id }}" data-callback="refreshNotes(false, false);"><i class="ion-ios-heart like"></i><i class="like-number">{{ likes }}</i></a>
            <a class="action category-link" href="#" data-action="follow/{{ name }}" data-callback="refreshNotes(false, false);"><i class="ion-person-add button-symbol" style="color:{{ followcolor }};"></i></a>
            <a class="category-link" href="/chats/with/{{ name }}"><i class="icon ion-ios-chatbubble"></i></a>
            <a class="action category-link" href="#" data-action="block/{{ name }}" data-callback="refreshNotes(false, false);"><i class="ion-close button-symbol"></i></a>
        </div>
    </td>
</tr>