<tr class="list-item-new">
    <td width="20%" align="right" style="padding:5px;">
        <div class="image-message">
            <a href="/profile/of/{{ note.profile.username }}">
            <img src="{{ note.profile.picture_public }}" width="100%" height="100%"/>
            </a>
        </div>
    </td>
    <td width="80%">
        <div>
            <span class="flag-icon flag-icon-ca user-country"></span>
            <h2 class="title-new inline">
                <a class="action-profile user-title" href="#" onclick="pizarra.pages.profile.show(pizarra.getProfile('{{ name }}'));" data-load="1">@{{ name }}</a>
            </h2>
            <span class="ion-female user-genre female"></span>
            <span class="notes-time">| {{ inserted }}</span>
        </div>
        <p class="note">
            {{ text }}
        </p>

        <div class="buttons-section">
            <a class="category-link" href="#" onclick="pizarra.actionLike('{{ id }}');"><i class="ion-ios-heart like"></i><i class="like-number">{{ likes }}</i></a>
            <a class="category-link" href="#" onclick="pizarra.actionFollow('{{ name }}');"><i class="ion-person-add button-symbol" style="color:{{ followcolor }};"></i></a>
            <a class="category-link" href="#" onclick="pizarra.pages.chat.show({friend: '{{ name }}', profile: pizarra.getCurrentProfile(false)});"><i class="icon ion-ios-chatbubble"></i></a>
            <a class="category-link" href="#" onclick="pizarra.actionBlock('{{ name }}');"><i class="ion-close button-symbol"></i></a>
        </div>
    </td>
</tr>