<div class="body padding notes">
    <div style="display:none;padding:0px;" id = "search-box">
         <br/>
        <p>Por favor escriba un @username, un #hashtag o un texto a buscar</p>
          <input type="text" class="w-input input-form" id="search-query" style="width:95%;">
    </div>

    <table style="display:none;" id="news-template">
    <?php include "_row.phtml"; ?>
    </table>

    <div class="news-mask"></div>
        <div class="news-container">
        <table id = "list-news" class="w-clearfix list-news">
            <!-- dynamic zone -->

            <?php
                foreach ($notes as $note)
                    echo Helper::parseTpl("feed/_row", [
                            [$note->profile, "note.profile.", ""],
                            [$note, "", ""]
                    ]);
            ?>
        </table>
        <br/><br/><br/><br/>
    </div>
</div>

<div class="w-clearfix input-chat-block shadowed-block">
    <div class="w-form">
        <div class="column-left">
            <div class="image-message notes-avatar"><a class = "show-edit" href="#" data-load="1">
				<img width="50" height="50" src="<?php echo $currentProfile->picture_public; ?>"></a>
            </div>
        </div>

        <input id="edtNote" class="w-input input-chat input-notes" id="chat-message" type="text" placeholder="Escribe una nueva nota..." name="nota" data-name="Nota">
        <input id="btnSendNote" class="w-button chat-button action-button" type="button" value="Enviar" data-wait="Por favor espere...">
    </div>
</div>

<script type="text/javascript">
<?php include "_events.js"; ?>
</script>