<div class="body padding notes">

    <?php if ($message !== false): ?>
        <br/>
        <div class="alert alert-<?php echo $message_type; ?>" role="alert" style="width: 50%; float: right;">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?php echo $message; ?>
        </div>
        <br/>
    <?php endif; ?>

    <?php include "_search_box.phtml"; ?>

    <textarea style="display:none;" id="news-template">
        <?php
        $tpl = Helper::getTemplate("feed/_row");
        echo base64_encode($tpl);
        ?>
        <?php /* include "_row.phtml";*/  ?>
    </textarea>

    <div class="news-mask"></div>
    <?php include "_row_note.phtml"; ?>
</div>

<div class="w-clearfix input-chat-block shadowed-block">
    <div class="w-form">
        <div class="column-left">
            <div class="image-message notes-avatar">
                <a href="/profile">
				    <img width="50" height="50" src="<?php echo $currentProfile->picture_public; ?>">
                </a>
            </div>
        </div>

        <input id="edtNote" class="w-input input-chat input-notes" id="chat-message" type="text" placeholder="Escribe una nueva nota..." name="nota" data-name="Nota">
        <input id="btnSendNote" class="w-button chat-button action-button" type="button" value="Enviar" data-wait="Por favor espere..." style="margin-right:20px;">
    </div>
</div>

<script type="text/javascript">
<?php include "index.js"; ?>
<?php include "search.js"; ?>
</script>