<tr class="list-item-new">
	<td width="50" align="right">
		<div class="image-message">
			<a href="/profile/of/{{ username }}" onclick = "$('#shadow-layer').show();">
				<img src="{{ picture }}" width="100%" height="100%"/>
			</a>
		</div>
	</td>
	<td style="padding-left:10px;">
		<div>
			<!-- <span class="flag-icon flag-icon-ca user-country"></span> -->
			<h2 class="title-new inline">
                <div style="display: table-cell; width:20px; float:left;">
                    <img src="" class="flag flag-{{ country }}" alt="{{ country }}" />
                </div>
                <a class="action-profile user-title" href="/chats/with/{{ username }}" onclick = "$('#shadow-layer').show();">@{{ username }}</a>
                <span class="ion-{{ gender }} user-genre {{ gender }}"></span>
                <span class="notes-time">| {{ inserted }}</span>
			</h2>
		</div>

		<p class="note">{{ text }}</p>

		<div class="buttons-section">
			<a class="action category-link {{ hideOwnLinks }}" href="#" data-action="like/{{ id }}" data-callback="$('#likes-{{ id }}').html(intval($('#likes-{{ id }}').html()) + 1);">
				<i class="ion-thumbsup like {{ isliked }}"></i><i id="likes-{{ id }}" class="like-number">{{ likes }}</i>
			</a>
            <a class="action category-link {{ hideOwnLinks }}" href="#" data-action="unlike/{{ id }}" data-callback="$('#unlikes-{{ id }}').html(intval($('#unlikes-{{ id }}').html()) + 1);">
                <i class="ion-thumbsdown"></i><i id="unlikes-{{ id }}" class="like-number">{{ unlikes }}</i>
            </a>
		</div>
	</td>
</tr>
