<tr class="list-item-new">
	<td width="40" align="right">
		<div class="image-message" style="width:40px;height:40px;">
			<a href="/profile/of/{{ username }}" onclick = "$('#shadow-layer').show();">
				<img src="{{ picture }}" width="100%" height="100%"/>
			</a>
		</div>
	</td>
	<td style="padding-left:10px;">
		<div>
			<h2 class="title-new inline" style="padding:0px;margin:0px;">
                <div style="display: table-cell; width:20px; float:left;">
                   <i class="flag flag-{{ country }}"></i>
                </div>
                <a class="action-profile user-title" href="/profile/of/{{ username }}" onclick = "$('#shadow-layer').show();">@{{ username }}</a>
                <span class="ion-{{ gender }} user-genre {{ gender }}"></span>
                <span class="notes-time">| {{ inserted }}</span>
			</h2>
		</div>

		<p class="note" style="padding:0px;margin:0px;">{{ text }}</p>

	</td>
</tr>
