<div class="body padding notes">
    <?php if ($message !== false): ?>
        <br/>
        <div class="alert alert-<?php echo $message_type; ?>" role="alert" style="width: 100%;">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?php echo $message; ?>
        </div>
        <br/>
    <?php endif; ?>
    <div class="news-container">
        <table id = "list-news" class="w-clearfix list-news">
           <?php
                echo Helper::parseTpl("feed/_row", [
                [$note, "", ""]
                ]);
            ?>
            <tr>
                <td>

                </td>
                <td>
                    <?php include "_row_comment.phtml"; ?>
                </td>
            </tr>
        </table>
        <br/><br/><br/><br/>
    </div>

    <textarea style="display:none;" id="news-template">
		<?php
        $tpl = Helper::getTemplate("note/_row");
        echo base64_encode($tpl);
        ?>
	</textarea>
</div>

<div class="w-clearfix input-chat-block shadowed-block">
    <div class="w-form">
        <div class="column-left">
            <div class="image-message notes-avatar">
                <a href="/profile" onclick = "$('#shadow-layer').show();">
                    <img width="50" height="50" src="<?php echo $currentProfile->picture_public; ?>">
                </a>
            </div>
        </div>
        <input id="edtNoteId" value="<?php echo $noteId;?>" type="hidden">
        <input id="edtNote" class="w-input input-chat input-notes" id="chat-message" type="text" placeholder="Escribe un nuevo comentario..." name="nota" data-name="Nota">
        <input id="btnSendNote" class="w-button chat-button action-button" type="button" value="Enviar" data-wait="Por favor espere..." style="margin-right:20px;">
    </div>
</div>

<script type="text/javascript">
    <?php include "index.js"; ?>
</script>
