<div class="w-clearfix input-chat-block shadowed-block">
    <div class="w-form">
        <div class="column-left">
            <div class="image-message notes-avatar">
                <a class = "show-edit" href="#" data-load="1">
                    <img src="{{ profile.picture_public }}" width="50" height="50">
                </a>
            </div>
        </div>

        <input id="edtNote" class="w-input input-chat input-notes" id="chat-message" type="text" placeholder="Escribe una nueva nota..." name="nota" data-name="Nota">
        <input id="btnSendNote" class="w-button chat-button action-button" type="button" value="Enviar" data-wait="Por favor espere...">
    </div>
</div>