<div class="w-clearfix input-chat-block shadowed-block">
    <div class="w-form">
        <div class="column-left">
            <div class="image-message notes-avatar">
                <a href = "/profile" onclick = "$('#shadow-layer').show();">
                    <img src="{{ profile.picture_public }}" width="50" height="50">
                </a>
            </div>
        </div>

        <input id="edtNote" maxlength="130" class="w-input input-chat input-notes" id="chat-message" type="text" placeholder="Escribe una nueva nota..." name="nota" data-name="Nota">
        <input id="btnSendNote" class="w-button chat-button action-button" type="button" value="Enviar" data-wait="Por favor espere...">
    </div>
</div>