<!-- left globe template -->
<li class="w-clearfix list-chat" >
    <div class="column-left chat">
        <div class="image-message chat chat-avatar">
            <a href="/profile/of/{{ note.profile.username }}" onclick = "$('#shadow-layer').show();">
                <img src="{{ note.profile.picture_public }}" width="100%" height="100%">
            </a>
        </div>
    </div>
    <div class="w-clearfix column-right chat">
        <div class="arrow-globe"></div>
        <div class="chat-text">{{ note.text }}</div>
        <div class="chat-time">{{ note.sent }}</div>
    </div>
</li>