<div class="body">

  <!-- left globe template -->
  <ul id="chat-left-template" style="display: none;">
    <li class="w-clearfix list-chat" >
      <div class="column-left chat">
        <div class="image-message chat chat-avatar">
          <a href="#" onclick="pizarra.pages.profile.show(pizarra.getProfile('{{ note.profile.username }}'));" data-load="1">
            <img src="{{ note.profile.picture_public }}" width="100%" height="100%">
          </a>
        </div>
      </div>
      <div class="w-clearfix column-right chat">
        <div class="arrow-globe"></div>
        <div class="chat-text">{{ note.text }}</div>
        <div class="chat-time">{{ note.sent }}</div>
      </div>
    </li>
  </ul>

  <!-- right globe template -->
  <ul id="chat-right-template" style="display: none;">
    <li class="list-chat right" >
      <div class="w-clearfix column-right chat right">
        <div class="arrow-globe right"></div>
        <div class="chat-text right">{{ note.text }}</div>
        <div class="chat-time right">{{ note.sent }}</div>
      </div>
    </li>
  </ul>
  <ul id = "chat-list" class="list list-chats">
  <!-- dynamic zone -->
  </ul>
</div>

<div class="w-clearfix input-chat-block shadowed-block">
  <div class="w-form">
    <div class="column-left">
      <div class="image-message notes-avatar">
        <a class = "show-edit" href="#" data-load="1">
          <img src="{{ profile.picture_public }}" width="50" height="50">
        </a>
      </div>
    </div>

    <input id="edtNote" class="w-input input-chat input-notes" id="chat-message" type="text" placeholder="Escribe una nueva nota..." name="nota" data-name="Nota">
    <input id="btnSendNote" class="w-button chat-button action-button" type="button" value="Enviar" data-wait="Por favor espere...">
  </div>
</div>

<script>
    $(function(){

        refreshChat(false, true);

        $("#btnSendNote").click(function(){ sendNote(); });

        $("#edtNote").on('keydown', function(e)
        {
            if (e.keyCode == 13)
                sendNote();
        });
    });

    function refreshChat(showLoading, force)
    {
        var timeout = 10000;

        if (pizarra.pages.current.name != 'chat')
            return;

        if (!isset(showLoading))
            showLoading = true;

        if (!isset(force))
            force = true;

        if ( ! force)
        {
            var items = pizarra.run("NOTA UNREAD", null, null, false);

            if (items.total < 1) {
                setTimeout("refreshChat(false, false);", timeout);
                return;
            }
        }

        var tplLeft = $("#chat-left-template").html();
        var tplRight = $("#chat-right-template").html();
        var notes = pizarra.run('NOTA @' + pizarra.pages.chat.data.friend, null,null,showLoading);
        var friendProfile =  pizarra.getProfile(pizarra.pages.chat.data.friend);

        if (friendProfile.picture != '1')
            friendProfile.picture_public = "images/user.png";

        //friendProfile.picture_public = pizarra.checkImage(friendProfile.picture_public);

        var allhtml = '';
        for (var i in notes.chats) {
            var tpl = tplLeft;
            var chat = notes.chats[i];
            if (chat.username == pizarra.currentProfile.username)
                tpl = tplRight;

            var html = tpl;

            html = pizarra.replaceTags(html, friendProfile, 'note.profile.');
            html = pizarra.replaceTags(html, chat, 'note.');

            allhtml = html + allhtml; // inverse order of notes

        }

        $("#chat-list").html(allhtml);
        //setTimeout('window.scrollTo(0, window.scrollMaxY)', 500);
        setTimeout('$(".body").slimscroll({scrollTo: "999px"})', 500);

        setTimeout("refreshChat(false, false);", timeout);
    }

    function sendNote(){
        if (pizarra.run('NOTA @' + pizarra.pages.chat.data.friend + " " + $("#edtNote").val(), null, null, false) != false)
        {
            $("#edtNote").val('');
            refreshChat(false, true);
        }
    }
</script>