<div class="body padding">

    <div class="separator-fields"></div>

    <ul id ="new-chat" class="list">
        <?php foreach($unread as $note): ?>
            <li class="list-message" >
                <a class="w-clearfix w-inline-block" href="/chats/with/<?php echo $note->username; ?>">
                    <div class="w-clearfix column-left">
                        <div class="image-message chat">
                            <img width="100%" height="100%" src="<?php echo $note->profile->picture_public; ?>">
                        </div>
                    </div>
                    <div class="column-right">
                        <span class="flag-icon flag-icon-cu user-country"></span>
                        <div class="message-title user-title"><b>@<?php echo $note->username; ?></b></div>
                    </div>
                </a>
            </li>
        <?php endforeach; ?>
    </ul>

    <div class="separator-fields"></div>

    <ul id="list" class="list">
        <?php foreach($notes as $note): ?>
        <li class="list-message">
            <a class="w-clearfix w-inline-block" href="/chats/with/<?php echo $note->profile->username; ?>">
                <div class="w-clearfix column-left">
                    <div class="image-message chat">
                        <img width="100%" height="100%" src="<?php echo $note->profile->picture_public; ?>">
                    </div>
                </div>
                <div class="column-right">
                    <span class="flag-icon flag-icon-cu user-country"></span>
                    <div class="message-title user-title">@<?php echo $note->profile->username; ?></div>
                    <div class="message-text"><?php echo $note->last_note->note; ?></div>
                </div>
            </a>
        </li>
        <?php endforeach; ?>
    </ul>
</div>

<script type="text/javascript">
<?php include "index.js"; ?>
</script>