<div class="body">

  <!-- left globe template -->
  <ul id="chat-left-template" class="hidden">
    <?php echo base64_encode(Helper::parseTpl("chats/_left")); ?>
  </ul>

  <!-- right globe template -->
  <ul id="chat-right-template" class="hidden">
      <?php echo base64_encode(Helper::parseTpl("chats/_right")); ?>
  </ul>

  <ul id = "chat-list" class="list list-chats">
      <!-- dynamic zone -->
        <?php

        $_left = Helper::getTemplate("chats/_left");
        $_right = Helper::getTemplate("chats/_right");

        $notes = array_reverse($notes);

        foreach ($notes as $note) {
            $_tpl = ($note->username == $currentProfile->username)? $_right : $_left;

            if ( ! isset($note->profile))
                $note->profile = $friendProfile;

            echo Helper::replaceTags($_tpl,[
                [$note, 'note.', ''],
                [$note->profile, 'note.profile.', '']
            ]);
        }
        ?>
  </ul>
</div>
<input id = "friend-username" type="hidden" value="<?php echo $friendProfile->username; ?>">
<?php echo Helper::parseTpl("chats/_chat_block"); ?>

<script type="text/javascript">
    <?php include "with.js"; ?>
    $(function(){
        pizarra.currentChat.chats = <?php echo json_encode(array_reverse($notes)); ?>;
        pizarra.friendUsername = '<?php echo $friendProfile->username; ?>';
    });
</script>