<?php $wwwhttp = $this->di->get('path')['http']; ?>
<?php $assets = $wwwhttp . "/res/"; ?>
<!DOCTYPE html>
<html class="w-mod-js w-mod-no-touch w-mod-video w-mod-no-ios wf-montserrat-n4-inactive wf-montserrat-n7-inactive wf-inactive">
<head>
    <meta charset="utf-8">
    <title>Pizarra</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

    <link rel="stylesheet" type="text/css" href="<?php echo $assets; ?>css/bootstrap.min.css">
    <!-- 3rd party styles -->
    <link rel="stylesheet" type="text/css" href="<?php echo $assets; ?>css/ionicons.min.css" />
    <!-- <link rel="stylesheet" type="text/css" href="<?php echo $assets; ?>css/normalize.css"> -->
    <link rel="stylesheet" type="text/css" href="<?php echo $assets; ?>css/jquery-ui.min.css">
    <!-- app styles -->
    <link rel="stylesheet" type="text/css" href="<?php echo $assets; ?>css/framework.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $assets; ?>css/pizarra.css">

    <?php $this->assets->outputCss(); ?>

    <!-- app icons -->
    <link rel="shortcut icon" type="image/x-icon" href="<?php echo $assets; ?>images/iconApretaste.png">
    <link rel="apple-touch-icon" href="<?php echo $assets; ?>images/iconApretaste.png">
    <link rel="shortcut icon" type="image/x-icon" href="<?php echo $assets; ?>images/logoApretaste.png">
    <link rel="apple-touch-icon" href="<?php echo $assets; ?>images/logoApretaste.png">

    <script type="text/javascript" src="<?php echo $assets; ?>js/jquery.min.js"></script>
</head>
<body>