<?php include "head.phtml"; ?>
<section class="w-section mobile-wrapper">
    <div class="page-content" id="main-stack">
        <div class="w-nav navbar" data-no-scroll="1" id="navbar">
            <div class="w-container" style="margin-right:10px;">
                <div class="wrapper-mask" data-ix="menu-mask"></div>
                <div class="hidden" id="navbar-title"></div>
                <a href="/"><img id = "logo" src="<?php echo $assets; ?>images/icon.png"></a>
                <a id="btnClose" class="w-inline-block navbar-button right" href="#" data-load="1" onclick="pizarra.pages.current.close();" >
                    <div class="navbar-button-icon icon ion-ios-close"></div>
                </a>
                <a id="btnRefresh" class="w-inline-block navbar-button right" href="#" data-load="1" onclick="pizarra.pages.current.refresh();">
                    <div class="navbar-button-icon icon ion-ios-refresh"></div>
                </a>
                <a id="btnPrevious" class="w-inline-block navbar-button right" href="#" data-load="1" onclick="pizarra.showPreviousPage();">
                    <div class="navbar-button-icon icon ion-ios-arrow-back"></div>
                </a>

                <!-- page notes buttons -->
                <a class="w-inline-block navbar-button right show-search-box top-buttons page-top-buttons page-notes-buttons" href="#" data-ix="">
                    <div class="navbar-button-icon icon ion-ios-search-strong"></div>
                </a>
                <a class="w-inline-block navbar-button right show-edit top-buttons page-top-buttons page-notes-buttons" href="<?php $wwwroot; ?>/profile">
                    <div class="navbar-button-icon icon ion-ios-person"></div>
                </a>
                <a class="w-inline-block navbar-button right show-chats top-buttons page-top-buttons page-notes-buttons" href="<?php $wwwroot; ?>/chats">
                    <div class="navbar-button-icon icon ion-ios-chatbubble"></div>
                </a>
            </div>
        </div>
        <?php echo $this->getContent(); ?>
    </div>
</section>

<?php include "foot.phtml"; ?>