<div class="body padding">
    <div class="logo-login"></div>
    <div class="padding">
        <div class="w-form">
            <div id="submit-form" data-name="Email Form">
                <div id="login-div">
                    <label class="label-form" for="email-field">EMAIL</label>
                    <div class="separator-fields"></div>
                    <input class="w-input input-form left" id="email-field" type="email" name="email" data-name="email" pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$" placeholder="Ingresa tu correo">
                    <input id="pass-button" class="w-button action-button" type="button" value="Siguiente" data-wait="Por favor espere...">
                    <div class="separator-fields"></div>
                </div>
                <div id="password-div" style="display:none;">
                    <p class="alert-text">Te hemos enviado un email. Por favor revisa e ingresa los 4 d&iacute;gitos que te hemos enviado en el campo debajo.</p>
                    <div class="separator-fields"></div>
                    <div class="w-clearfix block-input-combined">
                        <div class="separator-fields"></div>
                        <input type="button" class="w-button action-button" id ="login-back" value="&lt;" style="font-size: 22px; width:20%; height:65px; background: #ddd; color: gray;">
                        <input class="w-input input-form" data-name="password" type="password" id = "password" maxlength="4" style="width:79%;"/>
                    </div>
                    <input type="button" class="w-button action-button" id ="login-submit" value="INGRESAR">
                    <div class="separator-fields"></div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
   <?php include "index.js"; ?>
</script>