<div class="body">
	<div class="logo-login"></div>
	<div class="padding" style="width:90%; min-width:300px; max-width:400px; margin: auto; margin-top: 20px;">
		<div class="w-form">
			<div id="submit-form" data-name="Email Form">
				<div id="login-div">
					<label class="label-form" for="email-field">EMAIL</label>
					<div class="separator-fields"></div>
					<input class="w-input input-form left" id="email-field" type="email" name="email" data-name="email" pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$" placeholder="Ingresa tu correo">
					<input id="pass-button" class="w-button action-button" type="button" value="Siguiente" data-wait="Por favor espere...">
					<div class="separator-fields"></div>
				</div>
				<div id="password-div" style="display:none;">
					<p class="alert-text">Te hemos enviado un email. Por favor revisa e ingresa los 4 d&iacute;gitos que te hemos enviado en el campo debajo.</p>
					<div class="separator-fields"></div>
					<div class="w-clearfix block-input-combined">
						<div class="separator-fields"></div>
						<button type="button" class="w-button action-button" id ="login-back" value="&lt;"style="font-size: 22px; width:19%; height:65px; background: #ddd; color: gray;"><div class="navbar-button-icon icon ion-ios-arrow-back"></div></button>
						<input class="w-input input-form" data-name="text" type="numeric" id = "password" maxlength="4" style="width:79%; letter-spacing:0.8em; float:right;"/>
					</div>
					<input type="button" class="w-button action-button" id ="login-submit" value="ENTRAR">
					<div class="separator-fields"></div>
				</div>
			</div>
		</div>
	</div>
</div>

<script>
	<?php include "index.js"; ?>
</script>
