<div class="body padding">
    <br/>
    <div id="edit-image" class="profile-image">
        <img id ="picture" src="<?php echo $profile->picture_public; ?>" alt="@<?php echo $profile->username ; ?> en Pizarra" height="200" width="200"/>
    </div>
    <br/>
    <div class="grey-header">
        <h2 class="grey-heading-title profile-name text-centered">@<?php echo $profile->username ; ?></h2>
    </div>
    <div>
        <div class="separator-button"></div>
        <p class="description-new text-centered"><?php echo $profile->about_me ; ?></p>
        <div class="separator-button"></div>
    </div>
    <div>
        <?php if (count($profile->interests) > 0): ?>
        <div class="grey-header interests-header">
            <h2 class="grey-heading-title interests-title text-centered">Cosas que me interesan</h2>
        </div>

        <div id = "interests" style="text-align:center;">
            <?php foreach ($profile->interests as $interest): ?>
            <span> <?php echo $interest; ?></span>
            <?php endforeach; ?>
        </div>
        <?php endif; ?>
    </div>
    <div>
        <?php if ($currentProfile->username != $profile->username): ?>
        <div class="w-clearfix options-new">
            <?php if (!$profile->follow): ?>
            <a class="action w-clearfix w-inline-block action-button profile-button" data-action="follow/<?php echo $profile->username ; ?>" data-callback="$(this).hide();" data-showloading="true" href="#">
                <div class="icon-button bigger">
                    <div class="icon ion-person-add"></div>
                </div>
                Seguir
            </a>
            <?php endif; ?>
            <a href="<?php echo "/chats/with/{$profile->username}"; ?>" class="w-button w-inline-block action-button profile-button">
                <div class="icon-button bigger">
                    <div class="icon ion-ios-chatbubble"></div>
                </div>
                Chat
            </a>
        </div>
        <?php endif; ?>
    </div>
</div>

<script>
    $(function(){
        pizarra.reEvents();
    });
</script>