<div class="body padding">
    <div id="edit-image" class="profile-image">
        <img id= "picture" src="{{ picture_public }}" alt="@{{ username }} en Pizarra" />
    </div>
    <div class="grey-header">
        <h2 class="grey-heading-title profile-name text-centered">@{{ username }}</h2>
    </div>
    <div>
        <div class="separator-button"></div>
        <p class="description-new text-centered">{{ about_me }}
        <div class="separator-button"></div>
    </div>
    <div>
        <div class="grey-header interests-header" style="display:none;">
            <h2 class="grey-heading-title interests-title text-centered">Cosas que me interesan</h2>
        </div>

        <!-- interest template -->
        <div id="interest-template" style="display: none;">
            <div class="group-block interest">
                <div class="w-inline-block">
                    <div class="group-title">
                        <div class="title-text">{{ interests.value }}</div>
                    </div>
                </div>
            </div>
        </div>

        <div id = "interests" class="block-wrapper">
            <!-- dynamic zone -->
        </div>
    </div>
    <div>
        <div class="w-clearfix options-new">
            <a id="btnActionFollow" tag="{{ username }}" class="w-clearfix w-inline-block action-button profile-button" href="#" data-load="1">
                <div class="icon-button bigger">
                    <div class="icon ion-person-add"></div>
                </div>
                Seguir
            </a>
            <a onclick="pizarra.pages.chat.show({friend: '{{ username }}', profile: pizarra.getCurrentProfile(false)});" class="w-clearfix w-inline-block action-button profile-button" href="#" data-load="1">
                <div class="icon-button bigger">
                    <div class="icon ion-ios-chatbubble"></div>
                </div>
                Chat
            </a>
        </div>
    </div>
</div>

<script>
    $(function(){

        var tpl = $("#interest-template").html();

        var data = pizarra.pages.profile.data;

        if (!isset(data.interests))
            $(".interests-title").hide();

        if (count(data.interests) > 0)
            $(".interests-header").show();

        for (var i in data.interests)
        {
            var html = str_replace('{{ interests.value }}', data.interests[i], tpl);
            $("#interests").append(html);
        }

        $("#btnActionFollow").click(function(){
            pizarra.actionFollow($(this).attr('tag'));
            $(this).hide();
        });

        if (isset(data.follow))
            if (data.follow == true)
            {
                $("#btnActionFollow").hide();
            }
    });
</script>